Repository TeamTripmate/tripmate-android, pull requests merged in 2024-10, with the labels that each got.

#72 [fix] 홈화면 UI 디테일 보완, 마이페이지 티켓 내에 캐릭터 이미지 고정되는 이슈 해결
  core/common/build.gradle.kts
  core/common/src/main/kotlin/com/tripmate/android/core/common/utils/Character.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/LoadingWheel.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeFilterChips.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/navigation/HomeNavigation.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeViewModel.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/MyTripStyle.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/Ticket.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/PersonalizationActivity.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/component/MyTripStyle.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/TripDetailScreen.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/viewmodel/TripDetailUiAction.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/viewmodel/TripDetailViewModel.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/MyTripStyle.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/Ticket.kt
Labels: bug, hotfix, design

#73 [fit] TodoList 작업 진행
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeViewModel.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostViewModel.kt
  feature/mate-recruit-post/src/main/res/values/strings.xml
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateUiState.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/TripDetailScreen.kt
Labels: feature

#74 [fix] Loading indicator 로띠 애니메이션 적용, feature 모듈 내에 data 모듈 의존성 제거
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/assets/loading_animation.json
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/LoadingIndicator.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/LoadingWheel.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/NetworkImage.kt
  feature/home/build.gradle.kts
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeItem.kt
  feature/login/src/main/kotlin/com/tripmate/android/feature/login/LoginScreen.kt
  feature/map/build.gradle.kts
  feature/mate/build.gradle.kts
  feature/splash/src/main/kotlin/com/tripmate/android/feature/splash/SplashScreen.kt
  feature/trip-detail/build.gradle.kts
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/TripDetailScreen.kt
  feature/trip-list/build.gradle.kts
  feature/trip-original/build.gradle.kts
  gradle/libs.versions.toml
Labels: feature, refactor

#75 [fix] 여행 목록 및 전체적인 버그 수정
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MapRepositoryImpl.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Font.kt
  core/designsystem/src/main/res/values/strings.xml
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/TripmateService.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/MateRecruitScreen.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/MateReviewScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/MateScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/WithdrawScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyTripCharacterInfoViewModel.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/Question1Screen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/Question2Screen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/Question3Screen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/Question4Screen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/ResultScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/TripStyleScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/UserInfoScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiAction.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationViewModel.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/ReportScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateOpenChatScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/TripListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/MyTripStyle.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/PageIndicator.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/ReviewItems.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCard.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCardTeamLeader.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStyleTag.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/MateListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/MateOpenChatNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/TripListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/preview/MateSelectPreviewParameterProvider.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiAction.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiEvent.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiState.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListViewModel.kt
  feature/trip-list/src/main/res/values/strings.xml
  feature/trip-original/src/main/kotlin/com/tripmate/android/feature/trip_original/TripOriginalScreen.kt
  feature/trip-original/src/main/kotlin/com/tripmate/android/feature/trip_original/navigation/TripOriginalNavigation.kt
  gradle/libs.versions.toml
Labels: feature, hotfix, product, design

#77 [fix] 지도 보기 클릭 시 동행모집만 보기 Flag 초기화
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MapRepositoryImpl.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/SpotEntity.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/MateScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateUiState.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateViewModel.kt
  gradle/libs.versions.toml
Labels: feature, design

#79 [chore] 주소 정보가 없는 경우 주소 카테고리 예외처리
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeItem.kt
Labels: hotfix

#82 [fix] 동행 수락된 경우만 오픈카톡방 바로가기 버튼 보이도록 수정
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateOpenChatScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/TripListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/MateOpenChatNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/TripListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiAction.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiEvent.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListViewModel.kt
  gradle/libs.versions.toml
Labels: bug
