Repository TeamTripmate/tripmate-android, pull requests merged in 2024-09, with the labels that each got.

#42 [feat] 동행 후기 작성 화면 UI 구성 및 로직 구현
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Font.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/BadReviewEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/GoodReviewEntity.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/MateRecruitScreen.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/component/MateRecruitCheckBox.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/component/ScheduleDateTimePicker.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/navigation/MateRecruitNavigation.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/viewmodel/MateRecruitUiAction.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/viewmodel/MateRecruitUiEvent.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/viewmodel/MateRecruitUiState.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/viewmodel/MateRecruitViewModel.kt
  feature/mate-review/.gitignore
  feature/mate-review/build.gradle.kts
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/MateReviewScreen.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/component/MateReviewCheckBox.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/navigation/MateReviewNavigation.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/viewmodel/MateReviewUiAction.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/viewmodel/MateReviewUiEvent.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/viewmodel/MateReviewUiState.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/viewmodel/MateReviewViewModel.kt
  feature/mate-review/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feature, design

#43 [feat] [#25] 홈 화면 UI 구현
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Font.kt
  core/designsystem/src/main/res/drawable/ic_course.png
  core/designsystem/src/main/res/drawable/ic_culture.png
  core/designsystem/src/main/res/drawable/ic_dish.png
  core/designsystem/src/main/res/drawable/ic_heart_button.xml
  core/designsystem/src/main/res/drawable/ic_history.png
  core/designsystem/src/main/res/drawable/ic_hotel.png
  core/designsystem/src/main/res/drawable/ic_paint.png
  core/designsystem/src/main/res/drawable/ic_shopping.png
  core/designsystem/src/main/res/drawable/ic_show.png
  core/designsystem/src/main/res/drawable/ic_sports.png
  core/designsystem/src/main/res/drawable/ic_tree.png
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/FilterChip.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeFilterChips.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeItem.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/Tag.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiAction.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiEvent.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeViewModel.kt
  gradle/libs.versions.toml
Labels: feature

#44 [style] 마이페이지 화면 UI 구성
  core/data/src/main/kotlin/com/tripmate/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MyPageRepositoryImpl.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/NetworkImage.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_sample_character.png
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/MyPageRepository.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/MateRecruitScreen.kt
  feature/mate-recruit/src/main/kotlin/com/tripmate/android/feature/mate_recruit/component/ScheduleDateTimePicker.kt
  feature/mate-review/src/main/kotlin/com/tripmate/android/mate_review/MateReviewScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/DottedDivider.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/Ticket.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/navigation/MyPageNavigation.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiAction.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiEvent.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiState.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/res/values/strings.xml
Labels: design

#45 [feat] 여행지 상세페이지 화면 추가
  core/data/src/main/kotlin/com/tripmate/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/TripDetailRepositoryImpl.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Color.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/theme/Font.kt
  core/designsystem/src/main/res/drawable/ic_introduce.png
  core/designsystem/src/main/res/drawable/ic_location_pin.png
  core/designsystem/src/main/res/drawable/ic_mate_recruit_list.png
  core/designsystem/src/main/res/drawable/ic_recommend_style.png
  core/designsystem/src/main/res/drawable/ic_tips.png
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailMateRecruitEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailMateReviewEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailStyleEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/TripDetailRepository.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/tripdetail/build.gradle.kts
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/TripDetailScreen.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/component/DetailInfoTab.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/component/MateRecruitTab.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/component/MateReviewTab.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/navigation/TripDetailNavigation.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/viewmodel/TripDetailUiAction.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/viewmodel/TripDetailUiEvent.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/viewmodel/TripDetailUiState.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/viewmodel/TripDetailViewModel.kt
  settings.gradle.kts
Labels: feature, design

#49 [feat] 마이페이지 UI 변경 사항 반영, 내 여행 스타일 공유 기능 구현
  app/src/main/AndroidManifest.xml
  app/src/main/res/xml/provider_paths.xml
  core/common/src/main/kotlin/com/tripmate/android/core/common/extension/Context.kt
  core/common/src/main/kotlin/com/tripmate/android/core/common/utils/CreateBitmapFromPicture.kt
  core/common/src/main/kotlin/com/tripmate/android/core/common/utils/DpToPx.kt
  core/designsystem/src/main/res/drawable/img_character_01.png
  core/designsystem/src/main/res/drawable/img_character_02.png
  core/designsystem/src/main/res/drawable/img_character_03.png
  core/designsystem/src/main/res/drawable/img_character_04.png
  core/designsystem/src/main/res/drawable/img_character_05.png
  core/designsystem/src/main/res/drawable/img_character_06.png
  feature/mypage/build.gradle.kts
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyTripCharacterInfoScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/MyTripStyle.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/Ticket.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiAction.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiEvent.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageUiState.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyTripCharacterInfoViewModel.kt
  feature/mypage/src/main/res/drawable/ic_arrow_right_14.xml
  feature/mypage/src/main/res/drawable/ic_arrow_right_24.xml
  feature/mypage/src/main/res/values/strings.xml
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/ResultScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/component/AllTripStyles.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/component/MyTripStyle.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiAction.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiEvent.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiState.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationViewModel.kt
  feature/personalization/src/main/res/values/strings.xml
Labels: feature, design

#51 [feat] 동행 모집 글
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/MateRecruitPostEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailMateRecruitEntity.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/navigation/HomeNavigation.kt
  feature/main/build.gradle.kts
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mate-recruit-post/.gitignore
  feature/mate-recruit-post/build.gradle.kts
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/navigation/MateRecruitPostNavigation.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostUiAction.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostUiEvent.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostUiState.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostViewModel.kt
  feature/mate-recruit-post/src/main/res/values/strings.xml
  settings.gradle.kts
Labels: feature

#50 [chore] 내 근처 여행 -> 상세페이지 연동
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/MateScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/navigation/MateNavigation.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateUiAction.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateUiEvent.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateViewModel.kt
Labels: feature

#52 [feat] 여행 목록 디자인 및 신청자 목록 디자인
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TicketEntity.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/trip-list/build.gradle.kts
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/TripListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/PageIndicator.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/ReviewItems.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/Tag.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/Ticket.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TicketShape.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCard.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCardTeamLeader.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/MateListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/TripListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/preview/MateSelectPreviewParameterProvider.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiAction.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiEvent.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiState.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListViewModel.kt
Labels: feature

#54 [feature] 카카오톡 오픈 채팅방 진입 기능 구현
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/BadReviewEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/GenderAgeGroupEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/GoodReviewEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/WithdrawReasonEntity.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainNavController.kt
  feature/main/src/main/kotlin/com/tripmate/android/feature/main/MainScreen.kt
  feature/trip-list/build.gradle.kts
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateOpenChatScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/TripListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/MyTripStyle.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCard.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/MateOpenChatNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/navigation/TripListNavigation.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiAction.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiEvent.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiState.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListViewModel.kt
  feature/trip-list/src/main/res/values/strings.xml
Labels: feature

#56 [feat] Login API 연동
  core/data/src/main/kotlin/com/tripmate/android/core/data/di/RepositoryModule.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/mapper/dummy
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/AuthRepositoryImpl.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MyPageRepositoryImpl.kt
  core/datastore/src/main/kotlin/com/tripmate/android/core/datastore/TokenDataSource.kt
  core/datastore/src/main/kotlin/com/tripmate/android/core/datastore/TokenDataSourceImpl.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/UserInfoEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/AuthRepository.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/MyPageRepository.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/RetrofitQualifier.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/TokenInterceptor.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/di/ApiModule.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/di/NetworkModule.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/request/LoginRequest.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/request/WithdrawalRequest.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/UserInfoResponse.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/LoginService.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/TripmateService.kt
  feature/login/src/main/kotlin/com/tripmate/android/feature/login/LoginScreen.kt
  feature/login/src/main/kotlin/com/tripmate/android/feature/login/viewmodel/LoginViewModel.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/WithdrawViewModel.kt
Labels: feature

#59 [feat] 홈 화면 API 연결 및 디자인 수정
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MapRepositoryImpl.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/SpotEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/MapRepository.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/LocationBasedSpotSearchResponse.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/TripmateService.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeItem.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeUiState.kt
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/viewmodel/HomeViewModel.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/MateScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/viewmodel/MateViewModel.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/MateListScreen.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/Ticket.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/component/TripStatusCard.kt
  feature/trip-list/src/main/kotlin/com/tripmate/android/feature/trip_list/viewmodel/TripListUiState.kt
Labels: feature

#57 Feature/mate recruit post api
  core/data/src/main/kotlin/com/tripmate/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MateRepositoryImpl.kt
  core/designsystem/src/main/res/values/strings.xml
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/MateRecruitPostEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/MyPageUserInfoEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailMateRecruitEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripDetailMateReviewEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/UserInfoEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/MateRepository.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/MyPageRepository.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/request/CompanionApplyRequest.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/CompanionDetailInfoResponse.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/UserInfoResponse.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/TripmateService.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostUiAction.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostUiState.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostViewModel.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/TripDetailScreen.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/component/MateReviewTab.kt
  feature/tripdetail/src/main/kotlin/com/tripmate/android/feature/detailtrip/viewmodel/TripDetailUiState.kt
Labels: feature

#60 [feat] 개인화 설문 API 연동
  core/data/src/main/kotlin/com/tripmate/android/core/data/mapper/EntityToRequest.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/mapper/ResponseToEntity.kt
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/PersonalizationRepositoryImpl.kt
  core/designsystem/src/main/res/drawable/ic_kakao.xml
  core/designsystem/src/main/res/drawable/img_character_03.png
  core/designsystem/src/main/res/drawable/img_character_04.png
  core/designsystem/src/main/res/drawable/img_character_05.png
  core/designsystem/src/main/res/drawable/img_character_06.png
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/PersonalizedTestEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/PersonalizedTestResultEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/TripStyleEntity.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/repository/PersonalizationRepository.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/request/PersonalizedTestRequest.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/PersonalizedTestResultResponse.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/service/TripmateService.kt
  feature/login/src/main/kotlin/com/tripmate/android/feature/login/viewmodel/LoginViewModel.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/MyPageViewModel.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/viewmodel/WithdrawViewModel.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/ResultScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/UserInfoScreen.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/component/AllTripStyles.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/component/GenderSelectionBox.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiAction.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationUiState.kt
  feature/personalization/src/main/kotlin/com/tripmate/android/feature/personalization/viewmodel/PersonalizationViewModel.kt
Labels: feature

#63 [release] signingConfig 설정 추가, proguard rule 추가
  .github/workflows/android-ci.yml
  app/build.gradle.kts
  feature/login/proguard-rules.pro
  feature/personalization/proguard-rules.pro
Labels: feature, product

#65 Feature/mate detail api
  core/data/src/main/kotlin/com/tripmate/android/core/data/repository/MateRepositoryImpl.kt
  core/domain/src/main/kotlin/com/tripmate/android/domain/entity/MateRecruitPostEntity.kt
  core/network/src/main/kotlin/com/tripmate/android/core/network/response/CompanionDetailInfoResponse.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/viewmodel/MateRecruitPostViewModel.kt
Labels: feature

#69 [style] 이미지 속성 별(여행 아이템 이미지, 프로필 이미지) placeholder, failureImage 분기처리
  build-logic/src/main/kotlin/com/tripmate/android/Compose.kt
  core/designsystem/src/main/kotlin/com/tripmate/android/core/designsystem/component/NetworkImage.kt
  core/designsystem/src/main/res/drawable/img_profile_placeholder.png
  core/designsystem/src/main/res/drawable/img_sample_character.png
  core/designsystem/src/main/res/drawable/img_trip_placeholder.png
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/component/HomeItem.kt
  feature/mate-recruit-post/src/main/kotlin/com/tripmate/android/feature/mate_recruit_post/MateRecruitPostScreen.kt
  feature/mate/src/main/kotlin/com/tripmate/android/mate/MateScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/MyPageScreen.kt
  feature/mypage/src/main/kotlin/com/tripmate/android/feature/mypage/component/MyPickItem.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/TripDetailScreen.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/component/MateRecruitTab.kt
  gradle/libs.versions.toml
Labels: bug, hotfix, design

#70 [fix] QA
  feature/home/src/main/kotlin/com/tripmate/android/feature/home/HomeScreen.kt
  feature/trip-detail/src/main/kotlin/com/tripmate/android/feature/trip_detail/TripDetailScreen.kt
Labels: hotfix
